// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsbjHKSLmQqsvDFmMskCzZYuRsWqgb7Fw',
    appId: '1:325173757487:web:0c0582c0f0ce104cb3e8da',
    messagingSenderId: '325173757487',
    projectId: 'flutter-chat-app-5433f',
    authDomain: 'flutter-chat-app-5433f.firebaseapp.com',
    storageBucket: 'flutter-chat-app-5433f.appspot.com',
    measurementId: 'G-945Y5NE4G3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOugtMGgkbH_sAE5JzJ9dFEyosKa1qRRQ',
    appId: '1:325173757487:android:0790897902e37256b3e8da',
    messagingSenderId: '325173757487',
    projectId: 'flutter-chat-app-5433f',
    storageBucket: 'flutter-chat-app-5433f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqFU5aIRrdIIZVzZMGcpmHSqX39rKj33Y',
    appId: '1:325173757487:ios:1151b890c2ed6269b3e8da',
    messagingSenderId: '325173757487',
    projectId: 'flutter-chat-app-5433f',
    storageBucket: 'flutter-chat-app-5433f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqFU5aIRrdIIZVzZMGcpmHSqX39rKj33Y',
    appId: '1:325173757487:ios:963596c7e21f2b0db3e8da',
    messagingSenderId: '325173757487',
    projectId: 'flutter-chat-app-5433f',
    storageBucket: 'flutter-chat-app-5433f.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
